# Getting dressed

# target    prerequisite           command
# --------------------------------------------
coat:	    shoes mobile sweater;  @echo put on $@; touch $@
shoes:      socks trousers;        @echo put on $@; touch $@
mobile:     trousers;              @echo put on $@; touch $@
sweater:    shirt;		   @echo put on $@; touch $@
trousers:   pants shirt;           @echo put on $@; touch $@
shirt:      undershirt;            @echo put on $@; touch $@
socks:      ;                      @echo put on $@; touch $@
pants:      ;                      @echo put on $@; touch $@
undershirt: ;                      @echo put on $@; touch $@
